"""Dataclass configurations for Insight UI components.

This module provides type-safe configuration classes for all Insight UI template tags.
Using these dataclasses instead of plain dictionaries gives you:

- IDE autocompletion when creating configurations
- Static type checking with mypy
- Runtime validation via __post_init__
- Clear documentation of required and optional fields
- Reusable base classes for common patterns

Example usage:
    from insight_ui.configs import InputFieldConfig, SliderConfig

    # IDE shows all available fields with types
    email_field = InputFieldConfig(
        name="email",
        input_type="email",
        label="E-Mail Address",
        required=True,
    )

    price_slider = SliderConfig(
        name="price",
        label="Price Range",
        minimum=0,
        maximum=1000,
        dual=True,
    )
"""

from insight_ui.configs.base import DataAttrConfig, HtmxConfig, IconConfig, ImageConfig
from insight_ui.configs.card import (
    AppCardConfig,
    CardCarouselConfig,
    CardConfig,
    CarouselItemConfig,
    FlipCardConfig,
    ImageCarouselConfig,
    ImageCarouselItemConfig,
    ThreeDCarouselConfig,
    ToggleViewConfig,
)
from insight_ui.configs.filter import (
    FilterConfig,
    GenericFilterConfig,
    QueryBuilderConfig,
    QueryBuilderFieldConfig,
    SearchBarConfig,
)
from insight_ui.configs.forms import FormConfig, FormFieldConfig
from insight_ui.configs.input import (
    ButtonConfig,
    ChatConfig,
    CheckboxConfig,
    CheckboxGroupConfig,
    CheckboxItemConfig,
    DropdownConfig,
    DropdownItemConfig,
    InputFieldConfig,
    MultiselectConfig,
    RadioBlockConfig,
    RadioGroupConfig,
    RadioItemConfig,
    SelectConfig,
    SliderConfig,
    TextareaConfig,
    ToggleConfig,
)
from insight_ui.configs.layout import (
    ArticleConfig,
    DividerConfig,
    GridConfig,
    HBoxConfig,
    HeroConfig,
    PageConfig,
    PageHeaderConfig,
    SectionConfig,
    SpacerConfig,
    SurfaceConfig,
    VBoxConfig,
)
from insight_ui.configs.list import InfiniteScrollConfig, PaginationConfig, PaginationIppConfig, TableConfig
from insight_ui.configs.navigation import (
    AccordionConfig,
    AccordionItemConfig,
    BreadcrumbItemConfig,
    BreadcrumbsConfig,
    BulletPointItemConfig,
    BulletPointListConfig,
    FooterConfig,
    FooterContactConfig,
    FooterDescriptionConfig,
    LoginScreenConfig,
    MinimalStepperConfig,
    NavbarBrandConfig,
    NavbarConfig,
    NavbarLinkConfig,
    SidebarCategoryConfig,
    SidebarConfig,
    SidebarDataConfig,
    SidebarItemConfig,
    StepperConfig,
    StepperItemConfig,
    TabConfig,
    TabsConfig,
    UserMenuConfig,
    UserMenuLinkConfig,
)
from insight_ui.configs.popup import AlertConfig, ModalConfig
from insight_ui.configs.types import (
    ALERT_TYPE_VALUES,
    BADGE_TYPE_VALUES,
    BUTTON_TYPE_VALUES,
    COLOR_TYPE_VALUES,
    CORNER_POSITION_VALUES,
    FILTER_FIELD_TYPE_VALUES,
    FORM_FIELD_TYPE_VALUES,
    GEO_MAP_MARKER_TYPE_VALUES,
    HTML_BUTTON_TYPE_VALUES,
    HTML_INPUT_TYPE_VALUES,
    HTMX_METHOD_VALUES,
    HTMX_SWAP_METHOD_VALUES,
    INLINE_POSITION_VALUES,
    SIZE_VALUES,
    SLIDER_LEGEND_MODE_VALUES,
    STEP_STATUS_VALUES,
    TOGGLE_VIEW_TYPE_VALUES,
    AlertType,
    BadgeType,
    ButtonType,
    ColorType,
    CornerPosition,
    FilterFieldType,
    FormFieldType,
    GeoMapMarkerType,
    HtmlButtonType,
    HtmlInputType,
    HtmxMethod,
    HtmxSwapMethod,
    InlinePosition,
    Size,
    SliderLegendMode,
    StepStatus,
    ToggleViewType,
    validate_alert_type,
    validate_badge_type,
    validate_button_type,
    validate_color_type,
    validate_corner_position,
    validate_filter_field_type,
    validate_form_field_type,
    validate_geo_map_marker_type,
    validate_html_button_type,
    validate_html_input_type,
    validate_htmx_method,
    validate_htmx_swap_method,
    validate_inline_position,
    validate_size,
    validate_slider_legend_mode,
    validate_step_status,
    validate_toggle_view_type,
)
from insight_ui.configs.utils import (
    BadgeConfig,
    BrandMarkConfig,
    ChartConfig,
    ChartDatasetConfig,
    CopyrightNoticeConfig,
    CornerRibbonConfig,
    GeoMapConfig,
    GeoMapDatasetConfig,
    InfoboxConfig,
    LiveContentConfig,
    LogoConfig,
    ProgressBarConfig,
    StatusScreenConfig,
    WebSocketConfig,
)

__all__ = [
    "ALERT_TYPE_VALUES",
    "BADGE_TYPE_VALUES",
    "BUTTON_TYPE_VALUES",
    "COLOR_TYPE_VALUES",
    "CORNER_POSITION_VALUES",
    "FILTER_FIELD_TYPE_VALUES",
    "FORM_FIELD_TYPE_VALUES",
    "GEO_MAP_MARKER_TYPE_VALUES",
    "HTML_BUTTON_TYPE_VALUES",
    "HTML_INPUT_TYPE_VALUES",
    "HTMX_METHOD_VALUES",
    "HTMX_SWAP_METHOD_VALUES",
    "INLINE_POSITION_VALUES",
    "SIZE_VALUES",
    "SLIDER_LEGEND_MODE_VALUES",
    "STEP_STATUS_VALUES",
    "TOGGLE_VIEW_TYPE_VALUES",
    "AccordionConfig",
    "AccordionItemConfig",
    "AlertConfig",
    "AlertType",
    "AppCardConfig",
    "ArticleConfig",
    "BadgeConfig",
    "BadgeType",
    "BrandMarkConfig",
    "BreadcrumbItemConfig",
    "BreadcrumbsConfig",
    "BulletPointItemConfig",
    "BulletPointListConfig",
    "ButtonConfig",
    "ButtonType",
    "CardCarouselConfig",
    "CardConfig",
    "CarouselItemConfig",
    "ChartConfig",
    "ChartDatasetConfig",
    "ChatConfig",
    "CheckboxConfig",
    "CheckboxGroupConfig",
    "CheckboxItemConfig",
    "ColorType",
    "CopyrightNoticeConfig",
    "CornerPosition",
    "CornerRibbonConfig",
    "DataAttrConfig",
    "DividerConfig",
    "DropdownConfig",
    "DropdownItemConfig",
    "FilterConfig",
    "FilterFieldType",
    "FlipCardConfig",
    "FooterConfig",
    "FooterContactConfig",
    "FooterDescriptionConfig",
    "FormConfig",
    "FormFieldConfig",
    "FormFieldType",
    "GenericFilterConfig",
    "GeoMapConfig",
    "GeoMapDatasetConfig",
    "GeoMapMarkerType",
    "GridConfig",
    "HBoxConfig",
    "HeroConfig",
    "HtmlButtonType",
    "HtmlInputType",
    "HtmxConfig",
    "HtmxMethod",
    "HtmxSwapMethod",
    "IconConfig",
    "ImageCarouselConfig",
    "ImageCarouselItemConfig",
    "ImageConfig",
    "InfiniteScrollConfig",
    "InfoboxConfig",
    "InlinePosition",
    "InputFieldConfig",
    "LiveContentConfig",
    "LoginScreenConfig",
    "LogoConfig",
    "MinimalStepperConfig",
    "ModalConfig",
    "MultiselectConfig",
    "NavbarBrandConfig",
    "NavbarConfig",
    "NavbarLinkConfig",
    "PageConfig",
    "PageHeaderConfig",
    "PaginationConfig",
    "PaginationIppConfig",
    "ProgressBarConfig",
    "QueryBuilderConfig",
    "QueryBuilderFieldConfig",
    "RadioBlockConfig",
    "RadioGroupConfig",
    "RadioItemConfig",
    "SearchBarConfig",
    "SectionConfig",
    "SelectConfig",
    "SidebarCategoryConfig",
    "SidebarConfig",
    "SidebarDataConfig",
    "SidebarItemConfig",
    "Size",
    "SliderConfig",
    "SliderLegendMode",
    "SpacerConfig",
    "StatusScreenConfig",
    "StepStatus",
    "StepperConfig",
    "StepperItemConfig",
    "SurfaceConfig",
    "TabConfig",
    "TableConfig",
    "TabsConfig",
    "TextareaConfig",
    "ThreeDCarouselConfig",
    "ToggleConfig",
    "ToggleViewConfig",
    "ToggleViewType",
    "UserMenuConfig",
    "UserMenuLinkConfig",
    "VBoxConfig",
    "WebSocketConfig",
    "validate_alert_type",
    "validate_badge_type",
    "validate_button_type",
    "validate_color_type",
    "validate_corner_position",
    "validate_filter_field_type",
    "validate_form_field_type",
    "validate_geo_map_marker_type",
    "validate_html_button_type",
    "validate_html_input_type",
    "validate_htmx_method",
    "validate_htmx_swap_method",
    "validate_inline_position",
    "validate_size",
    "validate_slider_legend_mode",
    "validate_step_status",
    "validate_toggle_view_type",
]
