# Base paths
GIT_BASE_FILE = "https://github.com/alpininsight/insight-ui/blob/develop/insight_ui/templates/insight_ui/components/"
GIT_BASE_DIRECTORY = (
    "https://github.com/alpininsight/insight-ui/tree/develop/insight_ui/templates/insight_ui/components/"
)
GIT_BASE_SCRIPT_FILE = "https://github.com/alpininsight/insight-ui/blob/develop/insight_ui/static/insight_ui/js/"

# Mapping-Table between components and their respective template files
TEMPLATE_PATHS = {
    "card": GIT_BASE_FILE + "cards/card.html",
    "flip_card": GIT_BASE_FILE + "cards/flip_card.html",
    "app_card": GIT_BASE_FILE + "cards/app_card.html",
    "3D_carousel": GIT_BASE_FILE + "carousels/3D_carousel.html",
    "card_carousel": GIT_BASE_FILE + "carousels/card_carousel.html",
    "image_carousel": GIT_BASE_FILE + "carousels/image_carousel.html",
    "bar_chart": GIT_BASE_FILE + "charts/bar_chart.html",
    "line_chart": GIT_BASE_FILE + "charts/line_chart.html",
    "query_builder": GIT_BASE_DIRECTORY + "search_query_builder",
    "accordion": GIT_BASE_FILE + "accordion.html",
    "alert": GIT_BASE_FILE + "alert.html",
    "breadcrumbs": GIT_BASE_FILE + "breadcrumbs.html",
    "bullet_point_list": GIT_BASE_FILE + "bullet_point_list.html",
    "carousel": GIT_BASE_FILE + "carousel.html",
    "chat": GIT_BASE_FILE + "chat.html",
    "checkbox": GIT_BASE_FILE + "checkbox.html",
    "checkbox_group": GIT_BASE_FILE + "checkbox_group.html",
    "dropdown": GIT_BASE_FILE + "dropdown.html",
    "footer": GIT_BASE_FILE + "footer.html",
    "form": GIT_BASE_FILE + "form.html",
    "generic_filter": GIT_BASE_FILE + "generic_filter.html",
    "geo_map": GIT_BASE_FILE + "geo_map.html",
    "infinite_scroll": GIT_BASE_FILE + "infinite_scroll.html",
    "infobox": GIT_BASE_FILE + "infobox.html",
    "input": GIT_BASE_FILE + "input.html",
    "live_content": GIT_BASE_FILE + "live_content.html",
    "minimal_step_bar": GIT_BASE_FILE + "minimal_step_bar.html",
    "modal": GIT_BASE_FILE + "modal.html",
    "multiselect": GIT_BASE_FILE + "multiselect.html",
    "navbar": GIT_BASE_FILE + "navbar.html",
    "pagination": GIT_BASE_FILE + "pagination.html",
    "progress_bar": GIT_BASE_FILE + "progress_bar.html",
    "radio_block": GIT_BASE_FILE + "radio_block.html",
    "radio_group": GIT_BASE_FILE + "radio_group.html",
    "range_slider": GIT_BASE_FILE + "range_slider.html",
    "search_bar": GIT_BASE_FILE + "search_bar.html",
    "select": GIT_BASE_FILE + "select.html",
    "sidebar": GIT_BASE_FILE + "sidebar.html",
    "step_bar": GIT_BASE_FILE + "step_bar.html",
    "table": GIT_BASE_FILE + "table.html",
    "tabs": GIT_BASE_FILE + "tabs.html",
    "textarea": GIT_BASE_FILE + "textarea.html",
    "toggle_button": GIT_BASE_FILE + "toggle_button.html",
    "toggle_language": GIT_BASE_FILE + "toggle_language.html",
    "toggle_theme": GIT_BASE_FILE + "toggle_theme.html",
    "toggle_view": GIT_BASE_FILE + "toggle_view.html",
    "tooltip": GIT_BASE_FILE + "tooltip.html",
    "user_dropdown": GIT_BASE_FILE + "user_dropdown.html",
    "web_socket": GIT_BASE_FILE + "websocket.html",
    "page_header": GIT_BASE_FILE + "page_header.html",
    "heading_decoration": GIT_BASE_FILE + "heading_decoration.html",
    "article": GIT_BASE_FILE + "article.html",
    "hero": GIT_BASE_FILE + "hero.html",
}

# Mapping-Table between components and their respective script files
SCRIPT_PATHS = {
    "3D_carousel": GIT_BASE_SCRIPT_FILE + "insight-ui-3D-carousel.js",
    "accordion": GIT_BASE_SCRIPT_FILE + "insight-ui-accordion.js",
    "carousel": GIT_BASE_SCRIPT_FILE + "insight-ui-carousel.js",
    "checkbox_group": GIT_BASE_SCRIPT_FILE + "insight-ui-checkbox.js",
    "code_block": GIT_BASE_SCRIPT_FILE + "insight-ui-code_block.js",
    "collapsible": GIT_BASE_SCRIPT_FILE + "insight-ui-collapsible.js",
    "dropdown": GIT_BASE_SCRIPT_FILE + "insight-ui-dropdown.js",
    "tooltip": GIT_BASE_SCRIPT_FILE + "insight-ui-floater.js",
    "popover": GIT_BASE_SCRIPT_FILE + "insight-ui-floater.js",
    "modal": GIT_BASE_SCRIPT_FILE + "insight-ui-modal.js",
    "multiselect": GIT_BASE_SCRIPT_FILE + "insight-ui-multiselect.js",
    "toggle_language": GIT_BASE_SCRIPT_FILE + "insight-ui-select-language.js",
    "toggle_theme": GIT_BASE_SCRIPT_FILE + "insight-ui-theme-toggle.js",
    "sidebar": GIT_BASE_SCRIPT_FILE + "insight-ui-sidebar.js",
    "tabs": GIT_BASE_SCRIPT_FILE + "insight-ui-tabs.js",
    "websocket": GIT_BASE_SCRIPT_FILE + "insight-ui-websocket.js",
}
