# Paths are relative to the installed `insight_ui` package inside the running
# container. They are deliberately allowlisted before being exposed by views.
TEMPLATE_BASE = "templates/insight_ui/components/"
SCRIPT_BASE = "static/insight_ui/js/"

# Mapping-Table between components and their respective template files.
TEMPLATE_PATHS = {
    "card": TEMPLATE_BASE + "cards/card.html",
    "flip_card": TEMPLATE_BASE + "cards/flip_card.html",
    "app_card": TEMPLATE_BASE + "cards/app_card.html",
    "3d_carousel": TEMPLATE_BASE + "carousels/3D_carousel.html",
    "card_carousel": TEMPLATE_BASE + "carousels/card_carousel.html",
    "image_carousel": TEMPLATE_BASE + "carousels/image_carousel.html",
    "chart": TEMPLATE_BASE + "charts/bar_chart.html",
    "query_builder": TEMPLATE_BASE + "search_query_builder/sq_builder.html",
    "accordion": TEMPLATE_BASE + "accordion.html",
    "alert": TEMPLATE_BASE + "alert.html",
    "breadcrumbs": TEMPLATE_BASE + "breadcrumbs.html",
    "bullet_point_list": TEMPLATE_BASE + "bullet_point_list.html",
    "carousel": TEMPLATE_BASE + "carousel.html",
    "chat": TEMPLATE_BASE + "chat.html",
    "checkbox": TEMPLATE_BASE + "checkbox.html",
    "checkbox_group": TEMPLATE_BASE + "checkbox_group.html",
    "copyright_notice": TEMPLATE_BASE + "copyright_notice.html",
    "dropdown": TEMPLATE_BASE + "dropdown.html",
    "footer": TEMPLATE_BASE + "footer.html",
    "form": TEMPLATE_BASE + "form.html",
    "generic_filter": TEMPLATE_BASE + "generic_filter.html",
    "geo_map": TEMPLATE_BASE + "geo_map.html",
    "infinite_scroll": TEMPLATE_BASE + "infinite_scroll.html",
    "infobox": TEMPLATE_BASE + "infobox.html",
    "input_field": TEMPLATE_BASE + "input.html",
    "live_content": TEMPLATE_BASE + "live_content.html",
    "logo": TEMPLATE_BASE + "logo.html",
    "minimal_step_bar": TEMPLATE_BASE + "minimal_step_bar.html",
    "modal": TEMPLATE_BASE + "modal.html",
    "multiselect": TEMPLATE_BASE + "multiselect.html",
    "navbar": TEMPLATE_BASE + "navbar.html",
    "pagination": TEMPLATE_BASE + "pagination.html",
    "progress_bar": TEMPLATE_BASE + "progress_bar.html",
    "radio_block": TEMPLATE_BASE + "radio_block.html",
    "radio_group": TEMPLATE_BASE + "radio_group.html",
    "range_slider": TEMPLATE_BASE + "range_slider.html",
    "search_bar": TEMPLATE_BASE + "search_bar.html",
    "select": TEMPLATE_BASE + "select.html",
    "sidebar": TEMPLATE_BASE + "sidebar.html",
    "step_bar": TEMPLATE_BASE + "step_bar.html",
    "table": TEMPLATE_BASE + "table.html",
    "tabs": TEMPLATE_BASE + "tabs.html",
    "textarea": TEMPLATE_BASE + "textarea.html",
    "toggle": TEMPLATE_BASE + "toggle_button.html",
    "toggle_language": TEMPLATE_BASE + "toggle_language.html",
    "toggle_theme": TEMPLATE_BASE + "toggle_theme.html",
    "toggle_view": TEMPLATE_BASE + "toggle_view.html",
    "tooltip": TEMPLATE_BASE + "tooltip.html",
    "user_dropdown": TEMPLATE_BASE + "user_dropdown.html",
    "web_socket": TEMPLATE_BASE + "websocket.html",
    "page_header": TEMPLATE_BASE + "page_header.html",
    "heading_decoration": TEMPLATE_BASE + "heading_decoration.html",
    "article": TEMPLATE_BASE + "article.html",
    "hero": TEMPLATE_BASE + "hero.html",
    "corner_ribbon": TEMPLATE_BASE + "corner_ribbon.html",
}

# Mapping-Table between components and their respective script files.
SCRIPT_PATHS = {
    "3d_carousel": SCRIPT_BASE + "insight-ui-3D-carousel.js",
    "accordion": SCRIPT_BASE + "insight-ui-accordion.js",
    "carousel": SCRIPT_BASE + "insight-ui-carousel.js",
    "checkbox": SCRIPT_BASE + "insight-ui-checkbox.js",
    "checkbox_group": SCRIPT_BASE + "insight-ui-checkbox.js",
    "code_block": SCRIPT_BASE + "insight-ui-code-block.js",
    "collapsible": SCRIPT_BASE + "insight-ui-collapsible.js",
    "dropdown": SCRIPT_BASE + "insight-ui-dropdown.js",
    "tooltip": SCRIPT_BASE + "insight-ui-floater.js",
    "popover": SCRIPT_BASE + "insight-ui-floater.js",
    "modal": SCRIPT_BASE + "insight-ui-modal.js",
    "multiselect": SCRIPT_BASE + "insight-ui-multiselect.js",
    "range_slider": SCRIPT_BASE + "insight-ui-range-slider.js",
    "sidebar": SCRIPT_BASE + "insight-ui-sidebar.js",
    "tabs": SCRIPT_BASE + "insight-ui-tabs.js",
    "toggle_theme": SCRIPT_BASE + "insight-ui-theme-toggle.js",
    "web_socket": SCRIPT_BASE + "insight-ui-websocket.js",
}
